IMAGE_DICTS = {
    'Barley' : {
        '10Dec 19':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/GKYrltfzbIFRAd0',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/k1IIwo9XsF7pxyb',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/DLZFhDjV0KFLWn6'
        },
        '10Dec 24':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/xsIqHKknjKLONL9',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/gbsmf5UdwqHZpXn',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/RreGojhTnCHXRW8'
        },
        '10Dec 29':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/TdNPt65R0b94N5X',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/CqQhXaU1SWeiSP4',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/A4u39ifUR8jnwoK'
        },
        '10Dec 30':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/FxotDaDeeYimlaM',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/8Ff2WTK15PJF80Q',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/d2475BLnJ1wYq9s'
        },
        '18Mar 28':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/A68njFxi3wdpnOC',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/0ijPkHHBtbCCqHw',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/JcL47cfBJQrQ79Q'
        },
        '18Mar 31':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/VhBTnlA923NFdlS',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/qdbzvQoHOn07NuM',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/k6Mz1Vm4i8XolNa'
        },
        '18Mar 34':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/yQjGO8oCb9q8LPY',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/yC5T76FGfOC48wQ',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/P7uxtX9WrhkjzF4'
        },
        '18Mar 37':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/BDYwzQXbzTKqx9F',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/YoSGgHveWnTPLel',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/An6q34m85ZiVoGW'
        },
        '25Feb 27':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/DNHXGmsxB9UeWG3',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/mwPUv0oanRq67DV',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/0Wnxuc0W2ryyBcP'
        },
        '25Feb 29':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/sZCOqbu8772OOgy',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/hAMfYLPHhCSNkYB',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/ue3qjMJsGHb76YM'
        },
        '25Feb 32':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/fwygto1Upd33aLk',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/AveEgXsDEuc1bpk',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/JJTAe2xI75PPvrl'
        },
        '25Feb 37':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/P4w4oNaN210SX41',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/XpFeN4dxuQU8eIK',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/jhvHuYmzVSP3kLA'
        },
        '5Mar 10':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/pF7lI2fxBd7FlJb',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/hQ535U2TmyN2iNN',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/yTbPzD0EkvbE4FR'
        },
        '5Mar 3':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/ae3q8P2VaZOUxEq',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/mHhKDwcDhZcqQqZ',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/i3PcfBKWdbZaKTa'
        },
        '5Mar 6':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/InaQTbbjD9rOd8l',
            'predictions':
                'https://cloudstor.aarnet.edu.au/plus/s/RJy0vcoUseumSwv',
            'ground_truth':
                'https://cloudstor.aarnet.edu.au/plus/s/qWMAFgcwWVpHwzD'
        },
    },
    'Arabidopsis' : {
        'B-t-1-1':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/AMYCHSdmOgUFbKr',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'B-t-1-5':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/RJt9ny7k2PTNrgc',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'B-t-2-3':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/nTO1fFwwLDCeIUG',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-W-1-3':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/2ZC9oxmyGr6s483',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-W-2-2':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/MShWGRrOMIWyL03',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-g-1-1':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/cJKWUvteqEVa6gp',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-g-1-5':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/xu9pFhsIqmA9IDW',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-g-2-2':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/6kt5YZ9b3fpWA3u',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-t-1-2':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/iSvwR8DyvYDgX7k',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-t-2-1':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/T6vnVT726i1K0oq',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'B-t-1-3':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/rBccrjuu6k4iOP7',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'B-t-2-1':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/zYnsdy3g3jsUxwW',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-W-1-1':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/7fb54HQb4UTkkuk',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-W-1-6':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/mPGpY9PulN5Ji2N',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-W-2-4':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/CBkNoIhqDhiGW1p',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-g-1-3':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/zi1YZp7vWskX7fB',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-g-1-7':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/0lnJTwBBnoe3rIJ',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-g-2-4':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/NAsFbPPuWQmCw8w',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-t-1-4':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/2b6ldmBm5YKZ2Aq',
            'predictions':
                '',
            'ground_truth':
                ''
        },
        'C-t-2-4':{
            'image': 
                'https://cloudstor.aarnet.edu.au/plus/s/bjKK9bg9N5gHV5J',
            'predictions':
                '',
            'ground_truth':
                ''
        },
    }
}

EXTERNAL_DEPENDANCIES = {
    'barley_weights' : 
        'https://cloudstor.aarnet.edu.au/plus/s/KWFjWBLlE18n9M9',
    'barley_config' :
        'https://cloudstor.aarnet.edu.au/plus/s/qJztazXzBeOLO7E',
    'arabidopsis_weights' :
        '',
    'arabidopsis_config' :
        '',
}