services:
  sai-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: sai-app
    container_name: sai-app
    ports:
      - 80:8501
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
